// Copyright 2025 Democratized Data Foundation
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0, included in the file
// licenses/APL.txt.

package message

import (
	"context"
	"io"

	"github.com/fxamacker/cbor/v2"
	"github.com/gofrs/uuid/v5"
	"github.com/libp2p/go-libp2p/core/crypto"
	"github.com/libp2p/go-libp2p/core/host"
	"github.com/libp2p/go-libp2p/core/network"
	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/libp2p/go-libp2p/core/protocol"

	"github.com/sourcenetwork/defradb/errors"
)

// messageVersion is used to keep track of message format changes
// so that we can try to be backword compatible
const messageVersion = "/defradb/0.0.1"

// Message is the interface that protocol messages need to implement
// in order to be compatible with [Send] and [Receive].
//
// If messages embed the [MetaData] type they will automatically satisfy the interface.
type Message interface {
	// GetVersion returns the DefraDB message version.
	// This is a system defined version
	GetVersion() string
	// SetVersion sets the DefraDB message version on the struct
	SetVersion()
	// GetMessageID returns the message ID. It should be unique
	// for each request. Response message should contain the same
	// ID as the request so that responses can be handles properly.
	GetMessageID() string
	// SetMessageID sets the message ID on the struct. It should be unique
	// for each request. Response message should contain the same
	// ID as the request so that responses can be handles properly.
	SetMessageID(id string)
	// GetSenderID returns the ID of the sender. It will be a PeerID if
	// using libp2p.
	GetSenderID() string
	// SetSenderID sets the ID of the sender. It should be the ID of the node
	// creating the message. It will be a PeerID if using libp2p.
	SetSenderID(id string)
	// GetPubkey return the public key of the node that created the message.
	GetPubkey() []byte
	// SetPubkey sets the public key on the struct. It should be the public key
	// of the node creating the message and will be used to validate the
	// message signature
	SetPubkey(key []byte)
	// GetSignature returns the signature generated by the node that created the
	// message.
	GetSignature() []byte
	// SetSignature sets the signature value on the struct. This will be used by
	// the receiving node to validate the message authenticity.
	SetSignature(signature []byte)
	// GetErrMessage return an error string if one was set by the node responding
	// to the request.
	GetErrMessage() string
	// SetErrMessage set an error on the struct. It is used by the node responding
	// to a request to let the sending node know if something went wrong.
	SetErrMessage(err string)
}

// proto is the minum set of methods that protocols should implement to handle
// sending and receiving messages adequately.
type proto interface {
	Host() host.Host
	SetResponseChan(messageID string, message chan Message)
	DeleteResponseChan(messageID string)
	GetResponseChan(messageID string) (chan Message, bool)
}

// Reveive takes in a network stream and store the unmarshalled message in the provided [Message]
func Receive(s network.Stream, proto proto, m Message) error {
	b, err := io.ReadAll(s)
	if err != nil {
		resetErr := s.Reset()
		return errors.Join(err, resetErr)
	}
	err = s.Close()
	if err != nil {
		return err
	}

	err = cbor.Unmarshal(b, m)
	if err != nil {
		return err
	}

	err = verifyMessage(m)
	if err != nil {
		return err
	}

	messageChan, ok := proto.GetResponseChan(m.GetMessageID())
	if ok {
		messageChan <- m
		proto.DeleteResponseChan(m.GetMessageID())
	}

	return nil
}

// SendAndForget creates a new network stream with the provided peer, signs and set the appropriate meta data
// on the message and writes it to the stream.
//
// This function does not wait for the response.
func SendAndForget(
	ctx context.Context,
	proto proto,
	m Message,
	pid peer.ID,
	protoID protocol.ID,
) (err error) {
	err = signAndSetMetaData(proto.Host(), m)
	if err != nil {
		return err
	}
	return send(ctx, proto, m, pid, protoID)
}

// Send creates a new network stream with the provided peer, signs and set the appropriate meta data
// on the message and writes it to the stream.
//
// This blocks until a response is received. It is the responsibility of the caller to set a reasonable timeout.
func Send[ResponseType Message](
	ctx context.Context,
	proto proto,
	m Message,
	pid peer.ID,
	protoID protocol.ID,
) (resp ResponseType, err error) {
	err = signAndSetMetaData(proto.Host(), m)
	if err != nil {
		return resp, err
	}

	responseChan := make(chan Message, 1)
	proto.SetResponseChan(m.GetMessageID(), responseChan)

	err = send(ctx, proto, m, pid, protoID)
	if err != nil {
		proto.DeleteResponseChan(m.GetMessageID())
		close(responseChan)
		return resp, err
	}

	select {
	case respMessage := <-responseChan:
		if m.GetErrMessage() != "" {
			return resp, errors.New(respMessage.GetErrMessage())
		}
		switch typedResp := respMessage.(type) {
		case ResponseType:
			return typedResp, nil
		default:
			return resp, NewErrResponseType(resp, typedResp)
		}
	case <-ctx.Done():
		proto.DeleteResponseChan(m.GetMessageID())
		close(responseChan)
		return resp, ErrResponseTimeout
	}
}

// SendAsync creates a new network stream with the provided peer, signs and set the appropriate meta data
// on the message and writes it to the stream.
//
// It doesn't block for the response but instead provided a response channel for the
// to handle however they prefer. It is the responsibility of the caller to set a reasonable
// timeout otherwise this call will leak go routines and channels
func SendAsync[ResponseType Message](
	ctx context.Context,
	proto proto,
	m Message,
	pid peer.ID,
	protoID protocol.ID,
) (resp <-chan ResponseType, err error) {
	err = signAndSetMetaData(proto.Host(), m)
	if err != nil {
		return resp, err
	}

	responseChan := make(chan Message, 1)
	proto.SetResponseChan(m.GetMessageID(), responseChan)

	err = send(ctx, proto, m, pid, protoID)
	if err != nil {
		proto.DeleteResponseChan(m.GetMessageID())
		close(responseChan)
		return resp, err
	}

	funcResponseChan := make(chan ResponseType, 1)
	go func() {
		select {
		case respMessage := <-responseChan:
			switch typedResp := respMessage.(type) {
			case ResponseType:
				funcResponseChan <- typedResp
				close(funcResponseChan)
			default:
				close(funcResponseChan)
			}
		case <-ctx.Done():
			close(funcResponseChan)
			proto.DeleteResponseChan(m.GetMessageID())
			close(responseChan)
		}
	}()

	return funcResponseChan, nil
}

func send(
	ctx context.Context,
	proto proto,
	m Message,
	pid peer.ID,
	protoID protocol.ID,
) (err error) {
	data, err := cbor.Marshal(m)
	if err != nil {
		return err
	}

	s, err := proto.Host().NewStream(ctx, pid, protoID)
	if err != nil {
		return err
	}
	defer func() {
		closeErr := s.Close()
		err = errors.Join(err, closeErr)
	}()

	_, err = s.Write(data)
	if err != nil {
		resetErr := s.Reset()
		return errors.Join(err, resetErr)
	}
	return s.Close()
}

func verifyMessage(m Message) error {
	pubkey, err := crypto.UnmarshalPublicKey(m.GetPubkey())
	if err != nil {
		return err
	}
	idFromKey, err := peer.IDFromPublicKey(pubkey)
	if err != nil {
		return err
	}
	peerID, err := peer.Decode(m.GetSenderID())
	if err != nil {
		return err
	}
	if idFromKey != peerID {
		return ErrPubkeyPeerIDMismatch
	}

	signature := m.GetSignature()
	// To verify the signed message, the signature itself has to be removed from the struct.
	m.SetSignature(nil)
	b, err := cbor.Marshal(m)
	if err != nil {
		return err
	}

	valid, err := pubkey.Verify(b, signature)
	if err != nil {
		return err
	}
	if !valid {
		return ErrInvalidSignature
	}
	return nil
}

func signAndSetMetaData(h host.Host, m Message) error {
	// if the message ID is already set, its because the message is a response message.
	if m.GetMessageID() == "" {
		messageID, err := uuid.NewV4()
		if err != nil {
			return err
		}
		m.SetMessageID(messageID.String())
	}

	nodePubKey, err := crypto.MarshalPublicKey(h.Peerstore().PubKey(h.ID()))
	if err != nil {
		return err
	}
	m.SetVersion()
	m.SetPubkey(nodePubKey)
	m.SetSenderID(h.ID().String())

	signature, err := signMessage(h, m)
	if err != nil {
		return err
	}
	m.SetSignature(signature)
	return nil
}

func signMessage(h host.Host, m Message) ([]byte, error) {
	b, err := cbor.Marshal(m)
	if err != nil {
		return nil, err
	}
	key := h.Peerstore().PrivKey(h.ID())
	return key.Sign(b)
}
