// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sourcenetwork/defradb/client"
	"github.com/sourcenetwork/defradb/client/options"
	mock "github.com/stretchr/testify/mock"
)

// NewCollection creates a new instance of Collection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollection(t interface {
	mock.TestingT
	Cleanup(func())
}) *Collection {
	mock := &Collection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Collection is an autogenerated mock type for the Collection type
type Collection struct {
	mock.Mock
}

type Collection_Expecter struct {
	mock *mock.Mock
}

func (_m *Collection) EXPECT() *Collection_Expecter {
	return &Collection_Expecter{mock: &_m.Mock}
}

// AddDocument provides a mock function for the type Collection
func (_mock *Collection) AddDocument(ctx context.Context, doc *client.Document, opts ...options.Enumerable[options.AddDocumentOptions]) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, doc, opts)
	} else {
		tmpRet = _mock.Called(ctx, doc)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddDocument")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *client.Document, ...options.Enumerable[options.AddDocumentOptions]) error); ok {
		r0 = returnFunc(ctx, doc, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Collection_AddDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocument'
type Collection_AddDocument_Call struct {
	*mock.Call
}

// AddDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - doc *client.Document
//   - opts ...options.Enumerable[options.AddDocumentOptions]
func (_e *Collection_Expecter) AddDocument(ctx interface{}, doc interface{}, opts ...interface{}) *Collection_AddDocument_Call {
	return &Collection_AddDocument_Call{Call: _e.mock.On("AddDocument",
		append([]interface{}{ctx, doc}, opts...)...)}
}

func (_c *Collection_AddDocument_Call) Run(run func(ctx context.Context, doc *client.Document, opts ...options.Enumerable[options.AddDocumentOptions])) *Collection_AddDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *client.Document
		if args[1] != nil {
			arg1 = args[1].(*client.Document)
		}
		var arg2 []options.Enumerable[options.AddDocumentOptions]
		var variadicArgs []options.Enumerable[options.AddDocumentOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.AddDocumentOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_AddDocument_Call) Return(err error) *Collection_AddDocument_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Collection_AddDocument_Call) RunAndReturn(run func(ctx context.Context, doc *client.Document, opts ...options.Enumerable[options.AddDocumentOptions]) error) *Collection_AddDocument_Call {
	_c.Call.Return(run)
	return _c
}

// AddEncryptedIndex provides a mock function for the type Collection
func (_mock *Collection) AddEncryptedIndex(ctx context.Context, desc client.EncryptedIndexDescription, opts ...options.Enumerable[options.AddEncryptedIndexOptions]) (client.EncryptedIndexDescription, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, desc, opts)
	} else {
		tmpRet = _mock.Called(ctx, desc)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddEncryptedIndex")
	}

	var r0 client.EncryptedIndexDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.EncryptedIndexDescription, ...options.Enumerable[options.AddEncryptedIndexOptions]) (client.EncryptedIndexDescription, error)); ok {
		return returnFunc(ctx, desc, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.EncryptedIndexDescription, ...options.Enumerable[options.AddEncryptedIndexOptions]) client.EncryptedIndexDescription); ok {
		r0 = returnFunc(ctx, desc, opts...)
	} else {
		r0 = ret.Get(0).(client.EncryptedIndexDescription)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.EncryptedIndexDescription, ...options.Enumerable[options.AddEncryptedIndexOptions]) error); ok {
		r1 = returnFunc(ctx, desc, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Collection_AddEncryptedIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEncryptedIndex'
type Collection_AddEncryptedIndex_Call struct {
	*mock.Call
}

// AddEncryptedIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - desc client.EncryptedIndexDescription
//   - opts ...options.Enumerable[options.AddEncryptedIndexOptions]
func (_e *Collection_Expecter) AddEncryptedIndex(ctx interface{}, desc interface{}, opts ...interface{}) *Collection_AddEncryptedIndex_Call {
	return &Collection_AddEncryptedIndex_Call{Call: _e.mock.On("AddEncryptedIndex",
		append([]interface{}{ctx, desc}, opts...)...)}
}

func (_c *Collection_AddEncryptedIndex_Call) Run(run func(ctx context.Context, desc client.EncryptedIndexDescription, opts ...options.Enumerable[options.AddEncryptedIndexOptions])) *Collection_AddEncryptedIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.EncryptedIndexDescription
		if args[1] != nil {
			arg1 = args[1].(client.EncryptedIndexDescription)
		}
		var arg2 []options.Enumerable[options.AddEncryptedIndexOptions]
		var variadicArgs []options.Enumerable[options.AddEncryptedIndexOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.AddEncryptedIndexOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_AddEncryptedIndex_Call) Return(encryptedIndexDescription client.EncryptedIndexDescription, err error) *Collection_AddEncryptedIndex_Call {
	_c.Call.Return(encryptedIndexDescription, err)
	return _c
}

func (_c *Collection_AddEncryptedIndex_Call) RunAndReturn(run func(ctx context.Context, desc client.EncryptedIndexDescription, opts ...options.Enumerable[options.AddEncryptedIndexOptions]) (client.EncryptedIndexDescription, error)) *Collection_AddEncryptedIndex_Call {
	_c.Call.Return(run)
	return _c
}

// AddManyDocuments provides a mock function for the type Collection
func (_mock *Collection) AddManyDocuments(ctx context.Context, docs []*client.Document, opts ...options.Enumerable[options.AddDocumentOptions]) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, docs, opts)
	} else {
		tmpRet = _mock.Called(ctx, docs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddManyDocuments")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*client.Document, ...options.Enumerable[options.AddDocumentOptions]) error); ok {
		r0 = returnFunc(ctx, docs, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Collection_AddManyDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddManyDocuments'
type Collection_AddManyDocuments_Call struct {
	*mock.Call
}

// AddManyDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - docs []*client.Document
//   - opts ...options.Enumerable[options.AddDocumentOptions]
func (_e *Collection_Expecter) AddManyDocuments(ctx interface{}, docs interface{}, opts ...interface{}) *Collection_AddManyDocuments_Call {
	return &Collection_AddManyDocuments_Call{Call: _e.mock.On("AddManyDocuments",
		append([]interface{}{ctx, docs}, opts...)...)}
}

func (_c *Collection_AddManyDocuments_Call) Run(run func(ctx context.Context, docs []*client.Document, opts ...options.Enumerable[options.AddDocumentOptions])) *Collection_AddManyDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*client.Document
		if args[1] != nil {
			arg1 = args[1].([]*client.Document)
		}
		var arg2 []options.Enumerable[options.AddDocumentOptions]
		var variadicArgs []options.Enumerable[options.AddDocumentOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.AddDocumentOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_AddManyDocuments_Call) Return(err error) *Collection_AddManyDocuments_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Collection_AddManyDocuments_Call) RunAndReturn(run func(ctx context.Context, docs []*client.Document, opts ...options.Enumerable[options.AddDocumentOptions]) error) *Collection_AddManyDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// CollectionID provides a mock function for the type Collection
func (_mock *Collection) CollectionID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CollectionID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Collection_CollectionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectionID'
type Collection_CollectionID_Call struct {
	*mock.Call
}

// CollectionID is a helper method to define mock.On call
func (_e *Collection_Expecter) CollectionID() *Collection_CollectionID_Call {
	return &Collection_CollectionID_Call{Call: _e.mock.On("CollectionID")}
}

func (_c *Collection_CollectionID_Call) Run(run func()) *Collection_CollectionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Collection_CollectionID_Call) Return(s string) *Collection_CollectionID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Collection_CollectionID_Call) RunAndReturn(run func() string) *Collection_CollectionID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDocument provides a mock function for the type Collection
func (_mock *Collection) DeleteDocument(ctx context.Context, docID client.DocID, opts ...options.Enumerable[options.DeleteDocumentOptions]) (bool, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, docID, opts)
	} else {
		tmpRet = _mock.Called(ctx, docID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.DocID, ...options.Enumerable[options.DeleteDocumentOptions]) (bool, error)); ok {
		return returnFunc(ctx, docID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.DocID, ...options.Enumerable[options.DeleteDocumentOptions]) bool); ok {
		r0 = returnFunc(ctx, docID, opts...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.DocID, ...options.Enumerable[options.DeleteDocumentOptions]) error); ok {
		r1 = returnFunc(ctx, docID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Collection_DeleteDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocument'
type Collection_DeleteDocument_Call struct {
	*mock.Call
}

// DeleteDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docID client.DocID
//   - opts ...options.Enumerable[options.DeleteDocumentOptions]
func (_e *Collection_Expecter) DeleteDocument(ctx interface{}, docID interface{}, opts ...interface{}) *Collection_DeleteDocument_Call {
	return &Collection_DeleteDocument_Call{Call: _e.mock.On("DeleteDocument",
		append([]interface{}{ctx, docID}, opts...)...)}
}

func (_c *Collection_DeleteDocument_Call) Run(run func(ctx context.Context, docID client.DocID, opts ...options.Enumerable[options.DeleteDocumentOptions])) *Collection_DeleteDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.DocID
		if args[1] != nil {
			arg1 = args[1].(client.DocID)
		}
		var arg2 []options.Enumerable[options.DeleteDocumentOptions]
		var variadicArgs []options.Enumerable[options.DeleteDocumentOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.DeleteDocumentOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_DeleteDocument_Call) Return(b bool, err error) *Collection_DeleteDocument_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Collection_DeleteDocument_Call) RunAndReturn(run func(ctx context.Context, docID client.DocID, opts ...options.Enumerable[options.DeleteDocumentOptions]) (bool, error)) *Collection_DeleteDocument_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDocumentsWithFilter provides a mock function for the type Collection
func (_mock *Collection) DeleteDocumentsWithFilter(ctx context.Context, filter any, opts ...options.Enumerable[options.DeleteDocumentsWithFilterOptions]) (*client.DeleteResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocumentsWithFilter")
	}

	var r0 *client.DeleteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...options.Enumerable[options.DeleteDocumentsWithFilterOptions]) (*client.DeleteResult, error)); ok {
		return returnFunc(ctx, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...options.Enumerable[options.DeleteDocumentsWithFilterOptions]) *client.DeleteResult); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.DeleteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, ...options.Enumerable[options.DeleteDocumentsWithFilterOptions]) error); ok {
		r1 = returnFunc(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Collection_DeleteDocumentsWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocumentsWithFilter'
type Collection_DeleteDocumentsWithFilter_Call struct {
	*mock.Call
}

// DeleteDocumentsWithFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - opts ...options.Enumerable[options.DeleteDocumentsWithFilterOptions]
func (_e *Collection_Expecter) DeleteDocumentsWithFilter(ctx interface{}, filter interface{}, opts ...interface{}) *Collection_DeleteDocumentsWithFilter_Call {
	return &Collection_DeleteDocumentsWithFilter_Call{Call: _e.mock.On("DeleteDocumentsWithFilter",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *Collection_DeleteDocumentsWithFilter_Call) Run(run func(ctx context.Context, filter any, opts ...options.Enumerable[options.DeleteDocumentsWithFilterOptions])) *Collection_DeleteDocumentsWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []options.Enumerable[options.DeleteDocumentsWithFilterOptions]
		var variadicArgs []options.Enumerable[options.DeleteDocumentsWithFilterOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.DeleteDocumentsWithFilterOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_DeleteDocumentsWithFilter_Call) Return(deleteResult *client.DeleteResult, err error) *Collection_DeleteDocumentsWithFilter_Call {
	_c.Call.Return(deleteResult, err)
	return _c
}

func (_c *Collection_DeleteDocumentsWithFilter_Call) RunAndReturn(run func(ctx context.Context, filter any, opts ...options.Enumerable[options.DeleteDocumentsWithFilterOptions]) (*client.DeleteResult, error)) *Collection_DeleteDocumentsWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEncryptedIndex provides a mock function for the type Collection
func (_mock *Collection) DeleteEncryptedIndex(ctx context.Context, fieldName string, opts ...options.Enumerable[options.DeleteEncryptedIndexOptions]) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, fieldName, opts)
	} else {
		tmpRet = _mock.Called(ctx, fieldName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteEncryptedIndex")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...options.Enumerable[options.DeleteEncryptedIndexOptions]) error); ok {
		r0 = returnFunc(ctx, fieldName, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Collection_DeleteEncryptedIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEncryptedIndex'
type Collection_DeleteEncryptedIndex_Call struct {
	*mock.Call
}

// DeleteEncryptedIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - fieldName string
//   - opts ...options.Enumerable[options.DeleteEncryptedIndexOptions]
func (_e *Collection_Expecter) DeleteEncryptedIndex(ctx interface{}, fieldName interface{}, opts ...interface{}) *Collection_DeleteEncryptedIndex_Call {
	return &Collection_DeleteEncryptedIndex_Call{Call: _e.mock.On("DeleteEncryptedIndex",
		append([]interface{}{ctx, fieldName}, opts...)...)}
}

func (_c *Collection_DeleteEncryptedIndex_Call) Run(run func(ctx context.Context, fieldName string, opts ...options.Enumerable[options.DeleteEncryptedIndexOptions])) *Collection_DeleteEncryptedIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []options.Enumerable[options.DeleteEncryptedIndexOptions]
		var variadicArgs []options.Enumerable[options.DeleteEncryptedIndexOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.DeleteEncryptedIndexOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_DeleteEncryptedIndex_Call) Return(err error) *Collection_DeleteEncryptedIndex_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Collection_DeleteEncryptedIndex_Call) RunAndReturn(run func(ctx context.Context, fieldName string, opts ...options.Enumerable[options.DeleteEncryptedIndexOptions]) error) *Collection_DeleteEncryptedIndex_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIndex provides a mock function for the type Collection
func (_mock *Collection) DeleteIndex(ctx context.Context, indexName string, opts ...options.Enumerable[options.DeleteCollectionIndexOptions]) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, indexName, opts)
	} else {
		tmpRet = _mock.Called(ctx, indexName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteIndex")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...options.Enumerable[options.DeleteCollectionIndexOptions]) error); ok {
		r0 = returnFunc(ctx, indexName, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Collection_DeleteIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIndex'
type Collection_DeleteIndex_Call struct {
	*mock.Call
}

// DeleteIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - indexName string
//   - opts ...options.Enumerable[options.DeleteCollectionIndexOptions]
func (_e *Collection_Expecter) DeleteIndex(ctx interface{}, indexName interface{}, opts ...interface{}) *Collection_DeleteIndex_Call {
	return &Collection_DeleteIndex_Call{Call: _e.mock.On("DeleteIndex",
		append([]interface{}{ctx, indexName}, opts...)...)}
}

func (_c *Collection_DeleteIndex_Call) Run(run func(ctx context.Context, indexName string, opts ...options.Enumerable[options.DeleteCollectionIndexOptions])) *Collection_DeleteIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []options.Enumerable[options.DeleteCollectionIndexOptions]
		var variadicArgs []options.Enumerable[options.DeleteCollectionIndexOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.DeleteCollectionIndexOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_DeleteIndex_Call) Return(err error) *Collection_DeleteIndex_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Collection_DeleteIndex_Call) RunAndReturn(run func(ctx context.Context, indexName string, opts ...options.Enumerable[options.DeleteCollectionIndexOptions]) error) *Collection_DeleteIndex_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsDocument provides a mock function for the type Collection
func (_mock *Collection) ExistsDocument(ctx context.Context, docID client.DocID, opts ...options.Enumerable[options.ExistsDocumentOptions]) (bool, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, docID, opts)
	} else {
		tmpRet = _mock.Called(ctx, docID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExistsDocument")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.DocID, ...options.Enumerable[options.ExistsDocumentOptions]) (bool, error)); ok {
		return returnFunc(ctx, docID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.DocID, ...options.Enumerable[options.ExistsDocumentOptions]) bool); ok {
		r0 = returnFunc(ctx, docID, opts...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.DocID, ...options.Enumerable[options.ExistsDocumentOptions]) error); ok {
		r1 = returnFunc(ctx, docID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Collection_ExistsDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsDocument'
type Collection_ExistsDocument_Call struct {
	*mock.Call
}

// ExistsDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docID client.DocID
//   - opts ...options.Enumerable[options.ExistsDocumentOptions]
func (_e *Collection_Expecter) ExistsDocument(ctx interface{}, docID interface{}, opts ...interface{}) *Collection_ExistsDocument_Call {
	return &Collection_ExistsDocument_Call{Call: _e.mock.On("ExistsDocument",
		append([]interface{}{ctx, docID}, opts...)...)}
}

func (_c *Collection_ExistsDocument_Call) Run(run func(ctx context.Context, docID client.DocID, opts ...options.Enumerable[options.ExistsDocumentOptions])) *Collection_ExistsDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.DocID
		if args[1] != nil {
			arg1 = args[1].(client.DocID)
		}
		var arg2 []options.Enumerable[options.ExistsDocumentOptions]
		var variadicArgs []options.Enumerable[options.ExistsDocumentOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.ExistsDocumentOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_ExistsDocument_Call) Return(b bool, err error) *Collection_ExistsDocument_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Collection_ExistsDocument_Call) RunAndReturn(run func(ctx context.Context, docID client.DocID, opts ...options.Enumerable[options.ExistsDocumentOptions]) (bool, error)) *Collection_ExistsDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocument provides a mock function for the type Collection
func (_mock *Collection) GetDocument(ctx context.Context, docID client.DocID, opts ...options.Enumerable[options.GetDocumentOptions]) (*client.Document, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, docID, opts)
	} else {
		tmpRet = _mock.Called(ctx, docID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 *client.Document
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.DocID, ...options.Enumerable[options.GetDocumentOptions]) (*client.Document, error)); ok {
		return returnFunc(ctx, docID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.DocID, ...options.Enumerable[options.GetDocumentOptions]) *client.Document); ok {
		r0 = returnFunc(ctx, docID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Document)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.DocID, ...options.Enumerable[options.GetDocumentOptions]) error); ok {
		r1 = returnFunc(ctx, docID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Collection_GetDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocument'
type Collection_GetDocument_Call struct {
	*mock.Call
}

// GetDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docID client.DocID
//   - opts ...options.Enumerable[options.GetDocumentOptions]
func (_e *Collection_Expecter) GetDocument(ctx interface{}, docID interface{}, opts ...interface{}) *Collection_GetDocument_Call {
	return &Collection_GetDocument_Call{Call: _e.mock.On("GetDocument",
		append([]interface{}{ctx, docID}, opts...)...)}
}

func (_c *Collection_GetDocument_Call) Run(run func(ctx context.Context, docID client.DocID, opts ...options.Enumerable[options.GetDocumentOptions])) *Collection_GetDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.DocID
		if args[1] != nil {
			arg1 = args[1].(client.DocID)
		}
		var arg2 []options.Enumerable[options.GetDocumentOptions]
		var variadicArgs []options.Enumerable[options.GetDocumentOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.GetDocumentOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_GetDocument_Call) Return(document *client.Document, err error) *Collection_GetDocument_Call {
	_c.Call.Return(document, err)
	return _c
}

func (_c *Collection_GetDocument_Call) RunAndReturn(run func(ctx context.Context, docID client.DocID, opts ...options.Enumerable[options.GetDocumentOptions]) (*client.Document, error)) *Collection_GetDocument_Call {
	_c.Call.Return(run)
	return _c
}

// ListEncryptedIndexes provides a mock function for the type Collection
func (_mock *Collection) ListEncryptedIndexes(ctx context.Context, opts ...options.Enumerable[options.ListCollectionEncryptedIndexesOptions]) ([]client.EncryptedIndexDescription, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListEncryptedIndexes")
	}

	var r0 []client.EncryptedIndexDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...options.Enumerable[options.ListCollectionEncryptedIndexesOptions]) ([]client.EncryptedIndexDescription, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...options.Enumerable[options.ListCollectionEncryptedIndexesOptions]) []client.EncryptedIndexDescription); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.EncryptedIndexDescription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...options.Enumerable[options.ListCollectionEncryptedIndexesOptions]) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Collection_ListEncryptedIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEncryptedIndexes'
type Collection_ListEncryptedIndexes_Call struct {
	*mock.Call
}

// ListEncryptedIndexes is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...options.Enumerable[options.ListCollectionEncryptedIndexesOptions]
func (_e *Collection_Expecter) ListEncryptedIndexes(ctx interface{}, opts ...interface{}) *Collection_ListEncryptedIndexes_Call {
	return &Collection_ListEncryptedIndexes_Call{Call: _e.mock.On("ListEncryptedIndexes",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *Collection_ListEncryptedIndexes_Call) Run(run func(ctx context.Context, opts ...options.Enumerable[options.ListCollectionEncryptedIndexesOptions])) *Collection_ListEncryptedIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []options.Enumerable[options.ListCollectionEncryptedIndexesOptions]
		var variadicArgs []options.Enumerable[options.ListCollectionEncryptedIndexesOptions]
		if len(args) > 1 {
			variadicArgs = args[1].([]options.Enumerable[options.ListCollectionEncryptedIndexesOptions])
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Collection_ListEncryptedIndexes_Call) Return(encryptedIndexDescriptions []client.EncryptedIndexDescription, err error) *Collection_ListEncryptedIndexes_Call {
	_c.Call.Return(encryptedIndexDescriptions, err)
	return _c
}

func (_c *Collection_ListEncryptedIndexes_Call) RunAndReturn(run func(ctx context.Context, opts ...options.Enumerable[options.ListCollectionEncryptedIndexesOptions]) ([]client.EncryptedIndexDescription, error)) *Collection_ListEncryptedIndexes_Call {
	_c.Call.Return(run)
	return _c
}

// ListIndexes provides a mock function for the type Collection
func (_mock *Collection) ListIndexes(ctx context.Context, opts ...options.Enumerable[options.ListCollectionIndexesOptions]) ([]client.IndexDescription, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListIndexes")
	}

	var r0 []client.IndexDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...options.Enumerable[options.ListCollectionIndexesOptions]) ([]client.IndexDescription, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...options.Enumerable[options.ListCollectionIndexesOptions]) []client.IndexDescription); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.IndexDescription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...options.Enumerable[options.ListCollectionIndexesOptions]) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Collection_ListIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIndexes'
type Collection_ListIndexes_Call struct {
	*mock.Call
}

// ListIndexes is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...options.Enumerable[options.ListCollectionIndexesOptions]
func (_e *Collection_Expecter) ListIndexes(ctx interface{}, opts ...interface{}) *Collection_ListIndexes_Call {
	return &Collection_ListIndexes_Call{Call: _e.mock.On("ListIndexes",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *Collection_ListIndexes_Call) Run(run func(ctx context.Context, opts ...options.Enumerable[options.ListCollectionIndexesOptions])) *Collection_ListIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []options.Enumerable[options.ListCollectionIndexesOptions]
		var variadicArgs []options.Enumerable[options.ListCollectionIndexesOptions]
		if len(args) > 1 {
			variadicArgs = args[1].([]options.Enumerable[options.ListCollectionIndexesOptions])
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Collection_ListIndexes_Call) Return(indexDescriptions []client.IndexDescription, err error) *Collection_ListIndexes_Call {
	_c.Call.Return(indexDescriptions, err)
	return _c
}

func (_c *Collection_ListIndexes_Call) RunAndReturn(run func(ctx context.Context, opts ...options.Enumerable[options.ListCollectionIndexesOptions]) ([]client.IndexDescription, error)) *Collection_ListIndexes_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type Collection
func (_mock *Collection) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Collection_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Collection_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Collection_Expecter) Name() *Collection_Name_Call {
	return &Collection_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Collection_Name_Call) Run(run func()) *Collection_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Collection_Name_Call) Return(s string) *Collection_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Collection_Name_Call) RunAndReturn(run func() string) *Collection_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewIndex provides a mock function for the type Collection
func (_mock *Collection) NewIndex(context1 context.Context, newIndexRequest client.NewIndexRequest, vs ...options.Enumerable[options.NewCollectionIndexOptions]) (client.IndexDescription, error) {
	var tmpRet mock.Arguments
	if len(vs) > 0 {
		tmpRet = _mock.Called(context1, newIndexRequest, vs)
	} else {
		tmpRet = _mock.Called(context1, newIndexRequest)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for NewIndex")
	}

	var r0 client.IndexDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.NewIndexRequest, ...options.Enumerable[options.NewCollectionIndexOptions]) (client.IndexDescription, error)); ok {
		return returnFunc(context1, newIndexRequest, vs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.NewIndexRequest, ...options.Enumerable[options.NewCollectionIndexOptions]) client.IndexDescription); ok {
		r0 = returnFunc(context1, newIndexRequest, vs...)
	} else {
		r0 = ret.Get(0).(client.IndexDescription)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.NewIndexRequest, ...options.Enumerable[options.NewCollectionIndexOptions]) error); ok {
		r1 = returnFunc(context1, newIndexRequest, vs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Collection_NewIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewIndex'
type Collection_NewIndex_Call struct {
	*mock.Call
}

// NewIndex is a helper method to define mock.On call
//   - context1 context.Context
//   - newIndexRequest client.NewIndexRequest
//   - vs ...options.Enumerable[options.NewCollectionIndexOptions]
func (_e *Collection_Expecter) NewIndex(context1 interface{}, newIndexRequest interface{}, vs ...interface{}) *Collection_NewIndex_Call {
	return &Collection_NewIndex_Call{Call: _e.mock.On("NewIndex",
		append([]interface{}{context1, newIndexRequest}, vs...)...)}
}

func (_c *Collection_NewIndex_Call) Run(run func(context1 context.Context, newIndexRequest client.NewIndexRequest, vs ...options.Enumerable[options.NewCollectionIndexOptions])) *Collection_NewIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.NewIndexRequest
		if args[1] != nil {
			arg1 = args[1].(client.NewIndexRequest)
		}
		var arg2 []options.Enumerable[options.NewCollectionIndexOptions]
		var variadicArgs []options.Enumerable[options.NewCollectionIndexOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.NewCollectionIndexOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_NewIndex_Call) Return(indexDescription client.IndexDescription, err error) *Collection_NewIndex_Call {
	_c.Call.Return(indexDescription, err)
	return _c
}

func (_c *Collection_NewIndex_Call) RunAndReturn(run func(context1 context.Context, newIndexRequest client.NewIndexRequest, vs ...options.Enumerable[options.NewCollectionIndexOptions]) (client.IndexDescription, error)) *Collection_NewIndex_Call {
	_c.Call.Return(run)
	return _c
}

// SaveDocument provides a mock function for the type Collection
func (_mock *Collection) SaveDocument(ctx context.Context, doc *client.Document, opts ...options.Enumerable[options.SaveDocumentOptions]) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, doc, opts)
	} else {
		tmpRet = _mock.Called(ctx, doc)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SaveDocument")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *client.Document, ...options.Enumerable[options.SaveDocumentOptions]) error); ok {
		r0 = returnFunc(ctx, doc, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Collection_SaveDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDocument'
type Collection_SaveDocument_Call struct {
	*mock.Call
}

// SaveDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - doc *client.Document
//   - opts ...options.Enumerable[options.SaveDocumentOptions]
func (_e *Collection_Expecter) SaveDocument(ctx interface{}, doc interface{}, opts ...interface{}) *Collection_SaveDocument_Call {
	return &Collection_SaveDocument_Call{Call: _e.mock.On("SaveDocument",
		append([]interface{}{ctx, doc}, opts...)...)}
}

func (_c *Collection_SaveDocument_Call) Run(run func(ctx context.Context, doc *client.Document, opts ...options.Enumerable[options.SaveDocumentOptions])) *Collection_SaveDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *client.Document
		if args[1] != nil {
			arg1 = args[1].(*client.Document)
		}
		var arg2 []options.Enumerable[options.SaveDocumentOptions]
		var variadicArgs []options.Enumerable[options.SaveDocumentOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.SaveDocumentOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_SaveDocument_Call) Return(err error) *Collection_SaveDocument_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Collection_SaveDocument_Call) RunAndReturn(run func(ctx context.Context, doc *client.Document, opts ...options.Enumerable[options.SaveDocumentOptions]) error) *Collection_SaveDocument_Call {
	_c.Call.Return(run)
	return _c
}

// Truncate provides a mock function for the type Collection
func (_mock *Collection) Truncate(ctx context.Context, opts ...options.Enumerable[options.TruncateCollectionOptions]) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Truncate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...options.Enumerable[options.TruncateCollectionOptions]) error); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Collection_Truncate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Truncate'
type Collection_Truncate_Call struct {
	*mock.Call
}

// Truncate is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...options.Enumerable[options.TruncateCollectionOptions]
func (_e *Collection_Expecter) Truncate(ctx interface{}, opts ...interface{}) *Collection_Truncate_Call {
	return &Collection_Truncate_Call{Call: _e.mock.On("Truncate",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *Collection_Truncate_Call) Run(run func(ctx context.Context, opts ...options.Enumerable[options.TruncateCollectionOptions])) *Collection_Truncate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []options.Enumerable[options.TruncateCollectionOptions]
		var variadicArgs []options.Enumerable[options.TruncateCollectionOptions]
		if len(args) > 1 {
			variadicArgs = args[1].([]options.Enumerable[options.TruncateCollectionOptions])
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Collection_Truncate_Call) Return(err error) *Collection_Truncate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Collection_Truncate_Call) RunAndReturn(run func(ctx context.Context, opts ...options.Enumerable[options.TruncateCollectionOptions]) error) *Collection_Truncate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocument provides a mock function for the type Collection
func (_mock *Collection) UpdateDocument(ctx context.Context, docs *client.Document, opts ...options.Enumerable[options.UpdateDocumentOptions]) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, docs, opts)
	} else {
		tmpRet = _mock.Called(ctx, docs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocument")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *client.Document, ...options.Enumerable[options.UpdateDocumentOptions]) error); ok {
		r0 = returnFunc(ctx, docs, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Collection_UpdateDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocument'
type Collection_UpdateDocument_Call struct {
	*mock.Call
}

// UpdateDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docs *client.Document
//   - opts ...options.Enumerable[options.UpdateDocumentOptions]
func (_e *Collection_Expecter) UpdateDocument(ctx interface{}, docs interface{}, opts ...interface{}) *Collection_UpdateDocument_Call {
	return &Collection_UpdateDocument_Call{Call: _e.mock.On("UpdateDocument",
		append([]interface{}{ctx, docs}, opts...)...)}
}

func (_c *Collection_UpdateDocument_Call) Run(run func(ctx context.Context, docs *client.Document, opts ...options.Enumerable[options.UpdateDocumentOptions])) *Collection_UpdateDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *client.Document
		if args[1] != nil {
			arg1 = args[1].(*client.Document)
		}
		var arg2 []options.Enumerable[options.UpdateDocumentOptions]
		var variadicArgs []options.Enumerable[options.UpdateDocumentOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Enumerable[options.UpdateDocumentOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Collection_UpdateDocument_Call) Return(err error) *Collection_UpdateDocument_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Collection_UpdateDocument_Call) RunAndReturn(run func(ctx context.Context, docs *client.Document, opts ...options.Enumerable[options.UpdateDocumentOptions]) error) *Collection_UpdateDocument_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocumentsWithFilter provides a mock function for the type Collection
func (_mock *Collection) UpdateDocumentsWithFilter(ctx context.Context, filter any, updater string, opts ...options.Enumerable[options.UpdateDocumentsWithFilterOptions]) (*client.UpdateResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, updater, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter, updater)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentsWithFilter")
	}

	var r0 *client.UpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, string, ...options.Enumerable[options.UpdateDocumentsWithFilterOptions]) (*client.UpdateResult, error)); ok {
		return returnFunc(ctx, filter, updater, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, string, ...options.Enumerable[options.UpdateDocumentsWithFilterOptions]) *client.UpdateResult); ok {
		r0 = returnFunc(ctx, filter, updater, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.UpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, string, ...options.Enumerable[options.UpdateDocumentsWithFilterOptions]) error); ok {
		r1 = returnFunc(ctx, filter, updater, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Collection_UpdateDocumentsWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocumentsWithFilter'
type Collection_UpdateDocumentsWithFilter_Call struct {
	*mock.Call
}

// UpdateDocumentsWithFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - updater string
//   - opts ...options.Enumerable[options.UpdateDocumentsWithFilterOptions]
func (_e *Collection_Expecter) UpdateDocumentsWithFilter(ctx interface{}, filter interface{}, updater interface{}, opts ...interface{}) *Collection_UpdateDocumentsWithFilter_Call {
	return &Collection_UpdateDocumentsWithFilter_Call{Call: _e.mock.On("UpdateDocumentsWithFilter",
		append([]interface{}{ctx, filter, updater}, opts...)...)}
}

func (_c *Collection_UpdateDocumentsWithFilter_Call) Run(run func(ctx context.Context, filter any, updater string, opts ...options.Enumerable[options.UpdateDocumentsWithFilterOptions])) *Collection_UpdateDocumentsWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []options.Enumerable[options.UpdateDocumentsWithFilterOptions]
		var variadicArgs []options.Enumerable[options.UpdateDocumentsWithFilterOptions]
		if len(args) > 3 {
			variadicArgs = args[3].([]options.Enumerable[options.UpdateDocumentsWithFilterOptions])
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Collection_UpdateDocumentsWithFilter_Call) Return(updateResult *client.UpdateResult, err error) *Collection_UpdateDocumentsWithFilter_Call {
	_c.Call.Return(updateResult, err)
	return _c
}

func (_c *Collection_UpdateDocumentsWithFilter_Call) RunAndReturn(run func(ctx context.Context, filter any, updater string, opts ...options.Enumerable[options.UpdateDocumentsWithFilterOptions]) (*client.UpdateResult, error)) *Collection_UpdateDocumentsWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type Collection
func (_mock *Collection) Version() client.CollectionVersion {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 client.CollectionVersion
	if returnFunc, ok := ret.Get(0).(func() client.CollectionVersion); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(client.CollectionVersion)
	}
	return r0
}

// Collection_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type Collection_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *Collection_Expecter) Version() *Collection_Version_Call {
	return &Collection_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *Collection_Version_Call) Run(run func()) *Collection_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Collection_Version_Call) Return(collectionVersion client.CollectionVersion) *Collection_Version_Call {
	_c.Call.Return(collectionVersion)
	return _c
}

func (_c *Collection_Version_Call) RunAndReturn(run func() client.CollectionVersion) *Collection_Version_Call {
	_c.Call.Return(run)
	return _c
}

// VersionID provides a mock function for the type Collection
func (_mock *Collection) VersionID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for VersionID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Collection_VersionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VersionID'
type Collection_VersionID_Call struct {
	*mock.Call
}

// VersionID is a helper method to define mock.On call
func (_e *Collection_Expecter) VersionID() *Collection_VersionID_Call {
	return &Collection_VersionID_Call{Call: _e.mock.On("VersionID")}
}

func (_c *Collection_VersionID_Call) Run(run func()) *Collection_VersionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Collection_VersionID_Call) Return(s string) *Collection_VersionID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Collection_VersionID_Call) RunAndReturn(run func() string) *Collection_VersionID_Call {
	_c.Call.Return(run)
	return _c
}
