version: 2

before:
  hooks:
    - go mod tidy
    - make deps:playground

builds:
  # Minimal build with no extras
  - id: "defradb_slim"
    main: ./cmd/defradb
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  # Default build with playground
  - id: "defradb"
    main: ./cmd/defradb
    flags:
      - -tags=playground
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  # Default build with playground and telemetry
  - id: "defradb_telemetry"
    main: ./cmd/defradb
    flags:
      - -tags=playground,telemetry
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

partial:
  by: target

archives:
  - id: defradb_slim
    builds:
      - defradb_slim
    formats: [binary]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Binary }}_slim_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: defradb
    builds:
      - defradb
    formats: [binary]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Binary }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: defradb_telemetry
    builds:
      - defradb_telemetry
    formats: [binary]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Binary }}_telemetry_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  target_commitish: '{{ .Commit }}'
  header: >
    DefraDB v{{ .Major }}.{{ .Minor }} is a major pre-production release.
    Until the stable version 1.0 is reached, the SemVer minor patch number will denote notable releases,
    which will give the project freedom to experiment and explore potentially breaking changes.

    To get a full outline of the changes, we invite you to review the official changelog below.
    This release does include a Breaking Change to existing v{{ .Major }}.{{ .Minor }}.x databases.
    If you need help migrating an existing deployment, reach out at hello@source.network or join
    our Discord at https://discord.gg/w7jYQVJ/.

  name_template: "v{{ .Version }} Release"

changelog:
  sort: asc
  abbrev: -1
  groups:
    - title: Features
      regexp: '^feat:.*'
      order: 0
    - title: Fix
      regexp: '^fix:.*'
      order: 1
    - title: Tooling
      regexp: '^tools:.*'
      order: 2
    - title: Documentation
      regexp: '^docs:.*'
      order: 3
    - title: Refactoring
      regexp: '^refactor:.*'
      order: 4
    - title: Testing
      regexp: '^test:.*'
      order: 5

source:
  enabled: true

milestones:
  - close: true
    fail_on_error: false
    name_template: "DefraDB v{{ .Major }}.{{ .Minor }}"
