# Vale configuration for DefraDB documentation
StylesPath = styles
MinAlertLevel = suggestion
Packages = Google, write-good
Vocab = DefraDB

[*]
BasedOnStyles = Vale, Google, write-good, DefraDB

[*.{md,mdx}]
BasedOnStyles = Vale, Google, write-good, DefraDB

[docs/website/references/**/*.md]
DefraDB.Hedging = suggestion

[docs/website/references/cli/*.md]
Google.Headings = suggestion

[docs/data_format_changes/*.md]
DefraDB.Voice = NO
DefraDB.CorporateSpeak = suggestion
