# Copyright 2025 Democratized Data Foundation
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.

name: Check Data Format Changes Workflow

on:
  pull_request:
    branches:
      - master
      - develop

  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - master
      - develop

# Cancel the workflow if its in progress when there is a new commit. This will reduce unecessary resource usage.
concurrency:
  group: ${{ github.workflow }}-\
    ${{ github.ref == github.ref_protected && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-data-format-changes:
    name: Check data format changes job

    runs-on: runs-on=${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index }}/\
      spot=pco/cpu=16+32/family=c6*+c7*/disk=large/extras=s3-cache

    steps:
      - name: Enable RunsOn action
        uses: runs-on/action@v2
        with:
          metrics: cpu,network,memory,disk,io

      - name: Checkout code into the directory
        uses: actions/checkout@v6

      - name: Setup defradb
        uses: ./.github/composites/setup-defradb

      - name: Run data format change detection tests
        run: make test:changes
