# Copyright 2026 Democratized Data Foundation
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.

name: Validate Wizard Workflow

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - develop

jobs:
  test-wizard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Expect
        run: sudo apt-get update && sudo apt-get install -y expect
      - name: Build binary
        run: make build
      - name: Run wizard test
        run: |
          chmod +x ./tools/scripts/wizard_test.sh
          ./tools/scripts/wizard_test.sh
