# Copyright 2025 Democratized Data Foundation
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.

name: Test JS

on:
  pull_request:
    branches:
      - master
      - develop

  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - master
      - develop

jobs:
  # This job runs the JS tests to ensure they are able to build and run.
  test-js:
    name: Test JS job
    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: 0

    steps:
      - name: Checkout code into the directory
        uses: actions/checkout@v4

      - name: Setup defradb
        uses: ./.github/composites/setup-defradb

      # Disable AppArmor for Ubuntu 23.10+.
      # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Test JS
        run: make test:js
